name = input("my_string")
print(len(name.upper()))
print(len(name.lower()))
print(len(name.replace(" ", "")))
print(len(name[0]))
print(len(name[-1]))
print(name.upper())
print(name.lower())
print(name.replace(" ", ""))
print(name[0])
print(name[-1])